export let keywordAliases = {
  'asp': ['asp.net'],
  'net': ['asp.net'],
  'c': ['c#', 'c++'],
  'deep': ['deep learning'],
  'dev': ['devops'],
  'ops': ['devops'],
  'dj': ['django'],
  'go': ['golang'],
  'js': ['javascript'],
  'k8s': ['kubernetes'],
  'mongo': ['mongodb'],
  'node': ['node.js'],
  'ppt': ['powerpoint'],
  'py': ['python', 'pytorch'],
  'post': ['postgresql'],
  'scikit': ['scikit-learn'],
  'sklearn': ['scikit-learn'],
  'ts': ['typescript'],
  'rest': ['restful'],
  'tf': ['tensorflow'],
  'ai': ['ai工程師', '機器學習', 'machine learning', '深度學習', 'deep learning', 'keras', 'sklearn',
    'scikit-learn', 'tensorflow', 'pytorch', 'finetune', 'llm', 'nlp', 'transformer', '多模態', 'yolo', 'cnn'],
}
