export let keywordAliases = {
  'a11y': ['a11y', '無障礙', 'accessibility'],
  'admin': ['admin', '管理員', 'administrator'],
  'ai': ['ai工程師', '機器學習', '深度學習', '多模態', 'machine learning', 'deep learning', 'keras',
    'sklearn', 'scikit-learn', 'tensorflow', 'pytorch', 'finetune', 'fine-tune', 'fine-tuning',
    'llm', 'nlp', 'transformer', 'yolo', 'cnn', 'agent'],
  'asp': ['asp.net'],
  'auth': ['auth', '認證', 'authentication'],
  'authz': ['authz', '授權', 'authorization'],
  'c': ['c#', 'c++'],
  'db': ['db', '資料庫', 'database'],
  'deep': ['deep learning'],
  'dev': ['devops'],
  'dj': ['django'],
  'docs': ['docs', '文件', 'documentation'],
  'es': ['elasticsearch'],
  'ext': ['擴充功能', 'extension'],
  'go': ['golang'],
  'i18n': ['i18n', 'international'],
  'impl': ['實作', 'implementation'],
  'js': ['javascript'],
  'k8s': ['kubernetes'],
  'l10n': ['l10n', 'localization'],
  'mongo': ['mongodb'],
  'net': ['asp.net'],
  'node': ['node.js'],
  'o11y': ['o11y', '可觀測性', 'observability'],
  'ops': ['devops'],
  'post': ['postcss', 'postgres', 'postgresql'],
  'ppt': ['powerpoint'],
  'py': ['python', 'pytorch'],
  'repo': ['repo', 'git', 'gitHub', '分支', 'repository'],
  'rest': ['restful'],
  'scikit': ['scikit-learn'],
  'sklearn': ['scikit-learn'],
  'spec': ['規格', 'specification'],
  'tf': ['tensorflow'],
  'ts': ['typescript'],
}