export let keywordAliases = {
    'asp': ['asp.net'],
    'net': ['asp.net'],
    'c': ['c#', 'c++'],
    'deep': ['deep learning'],
    'dev': ['devops'],
    'ops': ['devops'],
    'dj': ['django'],
    'go': ['golang'],
    'js': ['javascript'],
    'k8s': ['kubernetes'],
    'mongo': ['mongodb'],
    'node': ['node.js'],
    'ppt': ['powerpoint'],
    'py': ['python', 'pytorch'],
    'post': ['postgresql'],
    'scikit': ['scikit-learn'],
    'ts': ['typescript'],
    'rest': ['restful'],
}
